### PR TITLE
Doc less perl

### PR DESCRIPTION
**Pull request by richsalz**
This removes more of the perl template stuff, replacing it with a small perl script.
Getting rid of all uses of the perl Template is one of the pre-reqs to moving to `cmake`

## Checklist
Thank you for your contribution. Please answer the following:

- [X] I acknowledge that I am authorized to submit this code under
the terms of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0)
- [ ] All new public APIs are documented
- [ ] All new public functions have tests
- [ ] All new public functions have fuzzing tests

### CODE REVIEW

**Review by wbl — DISMISSED** [review]

**Comment by richsalz** [comment]
Rebased and fixed merge conflicts in doc/man1/openssl-s_{client,server}.podin

**Comment by wbl** [comment]
I think we put another conflict back in

**Comment by richsalz** [comment]
Rebased, fixed conflicts (SRP is gone), squashed, and pushed.

**Review by wbl — APPROVED** [review]

**Comment by richsalz** [comment]
Added a commit to resolve conflict in the makefile template.

**Review by wbl — APPROVED** [review]

**Comment by richsalz** [comment]
THANKS!

**Pull request merged**
