### PR TITLE
Remove IRIX support.

### PR DESCRIPTION
**Pull request by richsalz**
## Checklist
Thank you for your contribution. Please answer the following:

- [X] I acknowledge that I am authorized to submit this code under
the terms of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Review by botovq — DISMISSED** [review]

**Review by botovq — APPROVED** [review]

**Comment by botovq** [comment]
I tried to resolve the trivial conflict. I believe you can approve and merge now.

**Comment by botovq** [comment]
I also can't approve/merge. Please force-push de37995422437e0c5a7655ce14b0a8bce0be28b0 again, then I guess you can resolve that conflict and I'll approve.

**Comment by richsalz** [comment]
I just made you a maintainer, so see if things work now.  Sorry, just learning GH permissions. :)

**Comment by botovq** [comment]
Thanks. The problem is not that.  The problem is hat github added a commit of mine on top of your PR branch, so I still can't merge: https://github.com/quictls/quictls/pull/95/commits/7a29b2c0f1a9fdce8a3be1f20eb33b795d5fd9a0. I don't know how to get rid of that commit other than force-pushing your old HEAD

**Comment by richsalz** [comment]
okay, applied the merge hammer.

**Review by botovq — APPROVED** [review]

**Comment by botovq** [comment]
The merge button is still greyed out here. I guess we need someone else to merge this...

**Review by botovq — DISMISSED** [review]

**Comment by botovq** [comment]
There's still a conflict here. Maybe we can merge when it's resolved? :)

**Comment by richsalz** [comment]
Ah, silly git.  Why it can't just merge `CHANGES.md`. Sigh.

**Review by botovq — APPROVED** [review]

**Pull request merged**
