### PR TITLE
Fix sockets.h: drop leading dashes

### PR DESCRIPTION
**Pull request by botovq**
## Checklist
Thank you for your contribution. Please answer the following:

- [x] I acknowledge that I am authorized to submit this code under
the terms of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by botovq** [comment]
These were well hidden in the github UI and broke CI.

**Review by richsalz — COMMENTED** [review]
sigh.

**Review by richsalz — APPROVED** [review]
Sigh was about my mistake.  Approved.

**Comment by botovq** [comment]
No worries that's how I took it (our mistake, in fact).

I think we should make it a habit to merge only if the CI is green. That's what it's for, after all.

**Comment by richsalz** [comment]
> I think we should make it a habit to merge only if the CI is green. That's what it's for, after all.

Yeah, you're probably right.  I need to slow my roll as the saying goes. :)

**Comment by botovq** [comment]
The [ABIDIFF test failed][1] because `make pristine` pulls from the [target main][2], which is currently broken, so I'm merging this.

```
 In file included from ../source-pristine/apps/include/apps.h:16,
                 from ../source-pristine/apps/lib/app_provider.c:10:
../source-pristine/include/internal/sockets.h:185:1: error: expected identifier or '(' before '-' token
  185 | -# if defined(OPENSSL_SYS_WIN32)
      | ^
```

[1]: https://github.com/quictls/quictls/actions/runs/11942008753/job/33288091146?pr=91#step:6:7
[2]: https://github.com/quictls/quictls/blob/47218de0070df55f8e858562ef15a8d353e637e9/.github/workflows/fips-checksums.yml#L31

**Pull request merged**
