### PR TITLE
Remove obsolete architectures

### PR DESCRIPTION
**Pull request by wbl**
## Checklist
Thank you for your contribution. Please answer the following:

- [x] I acknowledge that I am authorized to submit this code under
the terms of the [Apache License](https://www.apache.org/licenses/LICENSE-2.0)
- [x] All new public APIs are documented
- [x] All new public functions have tests
- [x] All new public functions have fuzzing tests

### CODE REVIEW

**Review by richsalz — APPROVED** [review]
Sure.  I wonder what @botovq thinks.  Merge, we can always restore if he tells us we went too far :)

**Review by richsalz — APPROVED** [review]

**Comment by wbl** [comment]
i'm going to wait for CI to finish

**Review by botovq — APPROVED** [review]
I'm fine with this. Not entirely sure about mips64. powerpc64 is interesting, but it's more interesting when used as BE arch. Hardware is quite rare and expensive.

Do you have any reason for wanting to keep s390? This has some nasty complicated tentacles that might be helpful to remove.

**Comment by wbl** [comment]
I should look at distribution policies but my sense was that they like
s390. The others are mostly embedded which isn't a space I think we care a
lot about given the other choices we are making.

**Pull request merged**
